package com.framework.examples.jsonplaceholder;

import com.framework.utils.RandomDataUtils;
import com.framework.utils.ValidationUtils;
import io.qameta.allure.Step;
import io.restassured.response.Response;
import jakarta.inject.Inject;

public class JsonPlaceholderScenario {

    private final PostSteps steps;

    @Inject
    public JsonPlaceholderScenario(PostSteps steps) {
        this.steps = steps;
    }

    @Step("Scenario: read a seed post + its comments, then simulate creating a new one")
    public void readPostWithCommentsThenSimulateCreate() {
        Response postResponse = steps.getPost(1);
        ValidationUtils.assertStatusCode(postResponse, 200);
        ValidationUtils.assertFieldExists(postResponse, "title");
        Post seedPost = postResponse.as(Post.class);

        Response commentsResponse = steps.getCommentsForPost(1);
        ValidationUtils.assertStatusCode(commentsResponse, 200);
        ValidationUtils.assertFieldExists(commentsResponse, "[0].email");

        Post newPost = Post.builder()
                .userId(seedPost.getUserId())
                .title(RandomDataUtils.faker().book().title())
                .body("Generated by the framework's example scenario.")
                .build();

        Response createResponse = steps.createPost(newPost);
        ValidationUtils.assertStatusCode(createResponse, 201);
        ValidationUtils.assertFieldExists(createResponse, "id");
        ValidationUtils.assertFieldEquals(createResponse, "title", newPost.getTitle());
    }
}
