name:
Nightly Regression


on:

 schedule:

  - cron:
      "0 2 * * *"


jobs:


 regression:


  runs-on:
    ubuntu-latest


  steps:


  - uses:
      actions/checkout@v4


  - name:
      Run regression


    run:

      mvn clean test \
      -Pacc \
      -Dgroups=regression